application: ucb-codereview 
version: test
runtime: python27
api_version: 1
threadsafe: false

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/upload.py
  script: main.application

- url: /static/(script.js|styles.css)
  static_files: static/\1
  upload: static/(script.js|styles.css)
  expiration: 1h  # Shorter expiration, these change often

- url: /static
  static_dir: static

- url: /tasks/migrate_entities
  script: main.application
  login: admin

- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.app
  login: admin

- url: /.*
  script: main.application

inbound_services:
- mail
- xmpp_message

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^env/(.*)

builtins:
- appstats: on
- remote_api: on
- deferred: on

libraries:
- name: django
  version: 1.5

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
